parameters:
- name: environment
  type: string
- name: dependsOn
  type: string

stages:
- stage: "DeployTo${{ parameters.environment }}"
  environment: ${{ parameters.environment }}
  dependsOn: ${{ parameters.dependsOn }}
  jobs: 
  - job: Deploy
    steps:
    - bash: echo "Hello world"
    - template: deploy_to_k8s.yml
      parameters:
        namespace: ${{ parameters.environment }}
